### ISSUE TITLE
Erro database.class.php line 67

### ISSUE THREAD

**Issue by valessiobrito** [dakous/speedtest#1]
[Thu Apr 23 17:09:24.085304 2015] [:error] [pid 715] [client 10.116.4.130:59674] PHP Fatal error:  Table 'speedtest.tbl_speedtests' doesn't exist<br/>\n\tSELECT\n\t\tbuild\n\tFROM\n\t\t`tbl_speedtests`\n\tWHERE\n\t\tDATE_FORMAT(`build`, '%Y%m%d') = ?\n\tGROUP BY\n\t\tDATE_FORMAT(`build`, '%Y%m%d')\n\tORDER BY\n\t\t`build` DESC\n in /var/www/html/speedtest/lib/database.class.php on line 67

**Comment by dakous** [comment]
Schema file added.
